# Generated by Django 5.1.4 on 2025-01-20 18:36

import django.db.models.deletion
import post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='MediaData',
            fields=[
                ('idMedia', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to=post.models.upload_to)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('post', models.ForeignKey(db_column='idPost', on_delete=django.db.models.deletion.CASCADE, related_name='url', to='post.post')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idComment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('url', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPost', models.ForeignKey(db_column='idPost', on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='RespondComment',
            fields=[
                ('idRespondComment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('url', models.ImageField(blank=True, null=True, upload_to=post.models.upload_image2)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idComment', models.ForeignKey(db_column='idComment', on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respondcomments',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('idLike', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPost', models.ForeignKey(db_column='idPost', on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('idPost', 'idUser')},
            },
        ),
    ]
