# Generated by Django 5.1.5 on 2025-02-15 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('idGoogle', models.CharField(max_length=245)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Username can only contain letters, numbers, '_' and '.'", regex='^[a-zA-Z0-9_.]+$')])),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=245, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ViewedUser',
            fields=[
                ('idViewedUser', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('idViewer', models.ForeignKey(db_column='idViewer', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewedusers',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('idFollow', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idFollower', models.ForeignKey(db_column='idFollower', on_delete=django.db.models.deletion.CASCADE, related_name='user_tap_follow', to=settings.AUTH_USER_MODEL)),
                ('idFollowing', models.ForeignKey(db_column='idFollowing', on_delete=django.db.models.deletion.CASCADE, related_name='user_is_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'unique_together': {('idFollower', 'idFollowing')},
            },
        ),
    ]
