# Generated by Django 5.1.4 on 2025-01-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('idGoogle', models.CharField(max_length=245)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=245, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profileImage', models.ImageField(blank=True, default='', null=True, upload_to='image/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('idFollow', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idFollower', models.ForeignKey(db_column='idFollower', on_delete=django.db.models.deletion.CASCADE, related_name='idFollower', to=settings.AUTH_USER_MODEL)),
                ('idFollowing', models.ForeignKey(db_column='idFollowing', on_delete=django.db.models.deletion.CASCADE, related_name='idFollowing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'unique_together': {('idFollower', 'idFollowing')},
            },
        ),
    ]
