# Generated by Django 5.1.5 on 2025-02-19 07:39

import comment.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idComment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('url', models.ImageField(blank=True, null=True, upload_to=comment.models.upload_image)),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idParentComment', models.ForeignKey(blank=True, db_column='idParentComment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment')),
                ('idPost', models.ForeignKey(db_column='idPost', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
                ('user', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('idCommentLike', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('idComment', models.ForeignKey(db_column='idComment', on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commentlikes',
            },
        ),
    ]
